// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"fmt"
	"testing"

	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
	"nickygin.com/recitewords/internal/models"
)

func init() {
	InitializeDB()
	err := db.AutoMigrate(&models.RcQueue{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&models.RcQueue{}) fail: %s", err)
	}
}

func Test_rcQueueQuery(t *testing.T) {
	rcQueue := newRcQueue(db)
	rcQueue = *rcQueue.As(rcQueue.TableName())
	_do := rcQueue.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(rcQueue.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <rc_queue> fail:", err)
		return
	}

	_, ok := rcQueue.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from rcQueue success")
	}

	err = _do.Create(&models.RcQueue{})
	if err != nil {
		t.Error("create item in table <rc_queue> fail:", err)
	}

	err = _do.Save(&models.RcQueue{})
	if err != nil {
		t.Error("create item in table <rc_queue> fail:", err)
	}

	err = _do.CreateInBatches([]*models.RcQueue{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <rc_queue> fail:", err)
	}

	_, err = _do.Select(rcQueue.ALL).Take()
	if err != nil {
		t.Error("Take() on table <rc_queue> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <rc_queue> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <rc_queue> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <rc_queue> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*models.RcQueue{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <rc_queue> fail:", err)
	}

	_, err = _do.Select(rcQueue.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <rc_queue> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <rc_queue> fail:", err)
	}

	_, err = _do.Select(rcQueue.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <rc_queue> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <rc_queue> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <rc_queue> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <rc_queue> fail:", err)
	}

	_, err = _do.ScanByPage(&models.RcQueue{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <rc_queue> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <rc_queue> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <rc_queue> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), "id")

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <rc_queue> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <rc_queue> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <rc_queue> fail:", err)
	}
}
