// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"nickygin.com/recitewords/internal/models"
)

func newRcUser(db *gorm.DB, opts ...gen.DOOption) rcUser {
	_rcUser := rcUser{}

	_rcUser.rcUserDo.UseDB(db, opts...)
	_rcUser.rcUserDo.UseModel(&models.RcUser{})

	tableName := _rcUser.rcUserDo.TableName()
	_rcUser.ALL = field.NewAsterisk(tableName)
	_rcUser.ID = field.NewInt32(tableName, "id")
	_rcUser.CreatedOn = field.NewTime(tableName, "created_on")
	_rcUser.ModifiedOn = field.NewTime(tableName, "modified_on")
	_rcUser.ModifiedBy = field.NewString(tableName, "modified_by")
	_rcUser.DeletedOn = field.NewTime(tableName, "deleted_on")
	_rcUser.IsDel = field.NewInt32(tableName, "is_del")
	_rcUser.LoginName = field.NewString(tableName, "login_name")
	_rcUser.LoginPwd = field.NewString(tableName, "login_pwd")
	_rcUser.Nickname = field.NewString(tableName, "nickname")
	_rcUser.RoleID = field.NewInt32(tableName, "role_id")

	_rcUser.fillFieldMap()

	return _rcUser
}

// rcUser 认证管理
type rcUser struct {
	rcUserDo rcUserDo

	ALL        field.Asterisk
	ID         field.Int32
	CreatedOn  field.Time   // 新建时间
	ModifiedOn field.Time   // 修改时间
	ModifiedBy field.String // 修改人
	DeletedOn  field.Time   // 删除时间
	IsDel      field.Int32  // 是否删除 0为未删除、1为已删除
	LoginName  field.String // Key
	LoginPwd   field.String // Secret
	Nickname   field.String
	RoleID     field.Int32

	fieldMap map[string]field.Expr
}

func (r rcUser) Table(newTableName string) *rcUser {
	r.rcUserDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r rcUser) As(alias string) *rcUser {
	r.rcUserDo.DO = *(r.rcUserDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *rcUser) updateTableName(table string) *rcUser {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt32(table, "id")
	r.CreatedOn = field.NewTime(table, "created_on")
	r.ModifiedOn = field.NewTime(table, "modified_on")
	r.ModifiedBy = field.NewString(table, "modified_by")
	r.DeletedOn = field.NewTime(table, "deleted_on")
	r.IsDel = field.NewInt32(table, "is_del")
	r.LoginName = field.NewString(table, "login_name")
	r.LoginPwd = field.NewString(table, "login_pwd")
	r.Nickname = field.NewString(table, "nickname")
	r.RoleID = field.NewInt32(table, "role_id")

	r.fillFieldMap()

	return r
}

func (r *rcUser) WithContext(ctx context.Context) *rcUserDo { return r.rcUserDo.WithContext(ctx) }

func (r rcUser) TableName() string { return r.rcUserDo.TableName() }

func (r rcUser) Alias() string { return r.rcUserDo.Alias() }

func (r rcUser) Columns(cols ...field.Expr) gen.Columns { return r.rcUserDo.Columns(cols...) }

func (r *rcUser) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *rcUser) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 10)
	r.fieldMap["id"] = r.ID
	r.fieldMap["created_on"] = r.CreatedOn
	r.fieldMap["modified_on"] = r.ModifiedOn
	r.fieldMap["modified_by"] = r.ModifiedBy
	r.fieldMap["deleted_on"] = r.DeletedOn
	r.fieldMap["is_del"] = r.IsDel
	r.fieldMap["login_name"] = r.LoginName
	r.fieldMap["login_pwd"] = r.LoginPwd
	r.fieldMap["nickname"] = r.Nickname
	r.fieldMap["role_id"] = r.RoleID
}

func (r rcUser) clone(db *gorm.DB) rcUser {
	r.rcUserDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r rcUser) replaceDB(db *gorm.DB) rcUser {
	r.rcUserDo.ReplaceDB(db)
	return r
}

type rcUserDo struct{ gen.DO }

func (r rcUserDo) Debug() *rcUserDo {
	return r.withDO(r.DO.Debug())
}

func (r rcUserDo) WithContext(ctx context.Context) *rcUserDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r rcUserDo) ReadDB() *rcUserDo {
	return r.Clauses(dbresolver.Read)
}

func (r rcUserDo) WriteDB() *rcUserDo {
	return r.Clauses(dbresolver.Write)
}

func (r rcUserDo) Session(config *gorm.Session) *rcUserDo {
	return r.withDO(r.DO.Session(config))
}

func (r rcUserDo) Clauses(conds ...clause.Expression) *rcUserDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r rcUserDo) Returning(value interface{}, columns ...string) *rcUserDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r rcUserDo) Not(conds ...gen.Condition) *rcUserDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r rcUserDo) Or(conds ...gen.Condition) *rcUserDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r rcUserDo) Select(conds ...field.Expr) *rcUserDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r rcUserDo) Where(conds ...gen.Condition) *rcUserDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r rcUserDo) Order(conds ...field.Expr) *rcUserDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r rcUserDo) Distinct(cols ...field.Expr) *rcUserDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r rcUserDo) Omit(cols ...field.Expr) *rcUserDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r rcUserDo) Join(table schema.Tabler, on ...field.Expr) *rcUserDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r rcUserDo) LeftJoin(table schema.Tabler, on ...field.Expr) *rcUserDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r rcUserDo) RightJoin(table schema.Tabler, on ...field.Expr) *rcUserDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r rcUserDo) Group(cols ...field.Expr) *rcUserDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r rcUserDo) Having(conds ...gen.Condition) *rcUserDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r rcUserDo) Limit(limit int) *rcUserDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r rcUserDo) Offset(offset int) *rcUserDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r rcUserDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *rcUserDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r rcUserDo) Unscoped() *rcUserDo {
	return r.withDO(r.DO.Unscoped())
}

func (r rcUserDo) Create(values ...*models.RcUser) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r rcUserDo) CreateInBatches(values []*models.RcUser, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r rcUserDo) Save(values ...*models.RcUser) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r rcUserDo) First() (*models.RcUser, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.RcUser), nil
	}
}

func (r rcUserDo) Take() (*models.RcUser, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.RcUser), nil
	}
}

func (r rcUserDo) Last() (*models.RcUser, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.RcUser), nil
	}
}

func (r rcUserDo) Find() ([]*models.RcUser, error) {
	result, err := r.DO.Find()
	return result.([]*models.RcUser), err
}

func (r rcUserDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.RcUser, err error) {
	buf := make([]*models.RcUser, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r rcUserDo) FindInBatches(result *[]*models.RcUser, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r rcUserDo) Attrs(attrs ...field.AssignExpr) *rcUserDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r rcUserDo) Assign(attrs ...field.AssignExpr) *rcUserDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r rcUserDo) Joins(fields ...field.RelationField) *rcUserDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r rcUserDo) Preload(fields ...field.RelationField) *rcUserDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r rcUserDo) FirstOrInit() (*models.RcUser, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.RcUser), nil
	}
}

func (r rcUserDo) FirstOrCreate() (*models.RcUser, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.RcUser), nil
	}
}

func (r rcUserDo) FindByPage(offset int, limit int) (result []*models.RcUser, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r rcUserDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r rcUserDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r rcUserDo) Delete(models ...*models.RcUser) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *rcUserDo) withDO(do gen.Dao) *rcUserDo {
	r.DO = *do.(*gen.DO)
	return r
}
