// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"fmt"
	"testing"

	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
	"nickygin.com/recitewords/internal/models"
)

func init() {
	InitializeDB()
	err := db.AutoMigrate(&models.UserClassKnowledge{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&models.UserClassKnowledge{}) fail: %s", err)
	}
}

func Test_userClassKnowledgeQuery(t *testing.T) {
	userClassKnowledge := newUserClassKnowledge(db)
	userClassKnowledge = *userClassKnowledge.As(userClassKnowledge.TableName())
	_do := userClassKnowledge.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(userClassKnowledge.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <user_class_knowledge> fail:", err)
		return
	}

	_, ok := userClassKnowledge.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from userClassKnowledge success")
	}

	err = _do.Create(&models.UserClassKnowledge{})
	if err != nil {
		t.Error("create item in table <user_class_knowledge> fail:", err)
	}

	err = _do.Save(&models.UserClassKnowledge{})
	if err != nil {
		t.Error("create item in table <user_class_knowledge> fail:", err)
	}

	err = _do.CreateInBatches([]*models.UserClassKnowledge{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <user_class_knowledge> fail:", err)
	}

	_, err = _do.Select(userClassKnowledge.ALL).Take()
	if err != nil {
		t.Error("Take() on table <user_class_knowledge> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <user_class_knowledge> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <user_class_knowledge> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <user_class_knowledge> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*models.UserClassKnowledge{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <user_class_knowledge> fail:", err)
	}

	_, err = _do.Select(userClassKnowledge.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <user_class_knowledge> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <user_class_knowledge> fail:", err)
	}

	_, err = _do.Select(userClassKnowledge.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <user_class_knowledge> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <user_class_knowledge> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <user_class_knowledge> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <user_class_knowledge> fail:", err)
	}

	_, err = _do.ScanByPage(&models.UserClassKnowledge{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <user_class_knowledge> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <user_class_knowledge> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <user_class_knowledge> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), "id")

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <user_class_knowledge> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <user_class_knowledge> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <user_class_knowledge> fail:", err)
	}
}
