// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameEnglishDictionary = "english_dictionary"

// EnglishDictionary 英语单词
type EnglishDictionary struct {
	ID           int32      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Word         *string    `gorm:"column:word;comment:英文单词" json:"word"`                                       // 英文单词
	CreatedOn    *time.Time `gorm:"column:created_on;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_on"` // 创建时间
	CreatedBy    *string    `gorm:"column:created_by;comment:创建人" json:"created_by"`                            // 创建人
	ModifiedOn   *time.Time `gorm:"column:modified_on;comment:修改时间" json:"modified_on"`                         // 修改时间
	ModifiedBy   *string    `gorm:"column:modified_by;comment:修改人" json:"modified_by"`                          // 修改人
	DeletedOn    *time.Time `gorm:"column:deleted_on;comment:删除时间" json:"deleted_on"`                           // 删除时间
	IsDel        *int32     `gorm:"column:is_del;comment:是否删除 0为未删除、1为已删除" json:"is_del"`                       // 是否删除 0为未删除、1为已删除
	State        *int32     `gorm:"column:state;default:1;comment:状态 0为禁用、1为启用" json:"state"`                   // 状态 0为禁用、1为启用
	Chinese      *string    `gorm:"column:chinese;comment:中文" json:"chinese"`                                   // 中文
	PartToSpeech *int32     `gorm:"column:part_to_speech;comment:词性" json:"part_to_speech"`                     // 词性
	WordClass    *int32     `gorm:"column:word_class;comment:词汇分级，如四六级单词" json:"word_class"`                    // 词汇分级，如四六级单词
	Pronounce    *[]byte    `gorm:"column:pronounce" json:"pronounce"`
}

// TableName EnglishDictionary's table name
func (*EnglishDictionary) TableName() string {
	return TableNameEnglishDictionary
}
