// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameRcUser = "rc_user"

// RcUser 认证管理
type RcUser struct {
	ID         int32      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedOn  *time.Time `gorm:"column:created_on;default:CURRENT_TIMESTAMP;comment:新建时间" json:"created_on"` // 新建时间
	ModifiedOn *time.Time `gorm:"column:modified_on;comment:修改时间" json:"modified_on"`                         // 修改时间
	ModifiedBy *string    `gorm:"column:modified_by;comment:修改人" json:"modified_by"`                          // 修改人
	DeletedOn  *time.Time `gorm:"column:deleted_on;comment:删除时间" json:"deleted_on"`                           // 删除时间
	IsDel      *int32     `gorm:"column:is_del;comment:是否删除 0为未删除、1为已删除" json:"is_del"`                       // 是否删除 0为未删除、1为已删除
	LoginName  string     `gorm:"column:login_name;not null;comment:Key" json:"login_name"`                   // Key
	LoginPwd   string     `gorm:"column:login_pwd;not null;comment:Secret" json:"login_pwd"`                  // Secret
	Nickname   string     `gorm:"column:nickname;not null" json:"nickname"`
	RoleID     *int32     `gorm:"column:role_id" json:"role_id"`
}

// TableName RcUser's table name
func (*RcUser) TableName() string {
	return TableNameRcUser
}
