// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameUserClass = "user_class"

// UserClass 用户笔记分类
type UserClass struct {
	ID               int32      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedOn        *time.Time `gorm:"column:created_on;default:CURRENT_TIMESTAMP;comment:新建时间" json:"created_on"` // 新建时间
	CreatedBy        *string    `gorm:"column:created_by;comment:创建人" json:"created_by"`                            // 创建人
	ModifiedOn       *time.Time `gorm:"column:modified_on;comment:修改时间" json:"modified_on"`                         // 修改时间
	ModifiedBy       *string    `gorm:"column:modified_by;comment:修改人" json:"modified_by"`                          // 修改人
	DeletedOn        *time.Time `gorm:"column:deleted_on;comment:删除时间" json:"deleted_on"`                           // 删除时间
	IsDel            *int32     `gorm:"column:is_del;comment:是否删除 0为未删除、1为已删除" json:"is_del"`                       // 是否删除 0为未删除、1为已删除
	Title            string     `gorm:"column:title;not null" json:"title"`
	ParentID         int32      `gorm:"column:parent_id;not null" json:"parent_id"`
	EnableToRemember *bool      `gorm:"column:enable_to_remember;default:1" json:"enable_to_remember"`
}

// TableName UserClass's table name
func (*UserClass) TableName() string {
	return TableNameUserClass
}
